### ISSUE TITLE
请问可以不断地塞入fmp4的segment进行播放吗？

### ISSUE THREAD

**Issue by huxiaoyingying** [studease/playease#10]
我服务器那边在不断采集摄像机的视频，并且将它的视频封装成fmp4的segment数据，通过websocket定时扔上来（实时数据），请问palyease有直接塞fmp4数据的接口吗

**Comment by studease** [comment]
可以，支持http和websocket的fmp4流。fmp4和flv模块是收费的，有需要加qq聊。

**Comment by oddengine** [comment]
> 我服务器那边在不断采集摄像机的视频，并且将它的视频封装成fmp4的segment数据，通过websocket定时扔上来（实时数据），请问palyease有直接塞fmp4数据的接口吗

可以，支持http和websocket的fmp4流。fmp4和flv模块是收费的，有需要加qq聊。

**Comment by huxiaoyingying** [comment]
qq是多少？
