### ISSUE TITLE
Missing file in compile script.

### ISSUE THREAD

**Issue by DLLDev** [studease/playease#11]
executing compile.sh shows
cat: ./release/odd.player.min.js: No such file or directory

**Comment by oddengine** [comment]
The player module is not open-sourced. You can download the odd.player.min.js at the [releases](https://github.com/oddcancer/odd.js/releases) page, then you'll be able to modify the other open-sourced part and compile them. The released odd.player.min.js can only play a stream from local IPs. If you are interested in it, we can settle a live broadcast on my site for testing. Or you'll have to buy a license.

The IM and WebRTC module is open-sourced, but should be used with our server, named as [oms](https://github.com/oddcancer/oms).
