### ISSUE TITLE
在华为浏览器中无法不放http-flv

### ISSUE THREAD

**Issue by xeon2007** [studease/playease#2]
华为P9，浏览器中无法播放http-flv直播流，chrome浏览器播放正常；
微信X5浏览器中第一次加载页面无法正常播放，点刷新按钮后播放正常；

**Comment by studease** [comment]
http://caniuse.com/#search=fetch

**Comment by studease** [comment]
这两天修复了部分浏览器适配，MSE需要较新的浏览器版本才支持

**Comment by xeon2007** [comment]
good job
