### ISSUE TITLE
oppo R9下微信打开播放器无法正常显示

### ISSUE THREAD

**Issue by xeon2007** [studease/playease#3]
oppo R9下微信打开播放器无法正常显示，播放窗口未能正常显示，安装chrome后，用chrome可以正常播放，如何确保微信直播的多种设备的可用性？

**Comment by studease** [comment]
目前我还没有找到移动端的调试方式，所以不清楚究竟是什么原因导致try或者直接的错误。据我所知，微信安卓版使用X5内核，可能它的一些MSE甚至JS接口是不标准的，要加X5前置（猜测）。chrome for android是有MSE功能的，它和PC端有一样的实现，所以能播flv。iOS上则使用safari内核，没有MSE接口，只能播HLS/MP4这些直接指定URL的类型。上周五的版本更新中已经发现了安卓的播放问题，我会继续跟进，也希望大家能提供一些意见和建议。

**Comment by xeon2007** [comment]
可以用微信开发者工具进行调试，ref：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455784140

**Comment by studease** [comment]
那个工具就是个chrome内核，还屏蔽了一些事件，测不了微信真实的环境。

**Comment by xeon2007** [comment]
X5 blink的真机调试是没问题的

**Comment by studease** [comment]
所以就需要在出问题的机子和环境下直接调试，可能系统和硬件上就有区别。

**Comment by xeon2007** [comment]
微信的x5应该对mse还不支持，目前看如果实现微信直播的话hls还是首选，fmp4还是需要个过程

**Comment by studease** [comment]
X5确实不支持
