### ISSUE TITLE
請問IE支援ws-flv嗎

### ISSUE THREAD

**Issue by MarsTsaiCoding** [studease/playease#5]
如標題

**Comment by oddengine** [comment]
https://www.caniuse.com/#search=mse
由于IE不支持MSE，无法使用H5方式解码，会使用flash，而flash中原生不支持websocket，只能http，所以目前不支持ws-flv。但是，可以在flash中实现websocket协议，再使用“数据生成模式”，就可以播放ws-flv。可以定制。

**Comment by MarsTsaiCoding** [comment]
@studease  這塊技術我比較薄弱，上面你講的這些我了解了，在請問一下你說的數據生成模式 可以用H5 canvas 去生成嗎

**Comment by studease** [comment]
> @studease 這塊技術我比較薄弱，上面你講的這些我了解了，在請問一下你說的數據生成模式 可以用H5 canvas 去生成嗎

**Comment by oddengine** [comment]
https://github.com/studease/playease-flash
这是flash模块的源码。
数据生成模式是flash的一种播放技术，和H5的MSE对应的，解码和渲染都是用的flash。canvas的话，首先是IE8中不支持（webgl 2.0在IE11中都不支持）；其次，软解码开销很大的，对IE来说性能更差，所以flash解码是更好的方式。

**Comment by oddengine** [comment]
之前为了在IE中支持websocket聊天，也是自己在flash中实现的协议，对服务端来说，只需要增加一个跨域策略文件。有这方面的需要的话，可以在群里连续我（TONY）。
