### ISSUE TITLE
buffer is full

### ISSUE THREAD

**Issue by yuhuatian** [studease/playease#6]
谷歌浏览器76，8路视频回直播流，播放大约2个小时，视频就断了，buffer is full.请问这个怎么解决

**Comment by oddengine** [comment]
原因是浏览器内核对缓冲区大小有限制，一般会出现在播放器录像的情况，所以播放录像的时候需要用xhr-chunked-loader这个loader去断点下载。

直播的话，目前播放器没有针对缓冲区做优化。
产生这错误的原因，通常是服务器发送数据的速度与服务器解码速度不匹配，比如时间戳有问题，或者因为tcp累积延迟。
可能的解决方案：在各个render里面，比如renders.flv里面定期检测缓冲区大小，使用加速播放，让播放器的缓冲区始终小等于配置里面的缓冲区（比如配置成3秒）。这个功能后面会考虑增加。

**Comment by Cojad** [comment]
如何加速播放? 目前我只能做到video.currentTime=video.buffered.end(0)直接跳到最底, 
但如果可以加速播放讓影片順暢的追到目前的最新buffer會是更好的選擇.

**Comment by oddengine** [comment]
> 如何加速播放? 目前我只能做到video.currentTime=video.buffered.end(0)直接跳到最底,
> 但如果可以加速播放讓影片順暢的追到目前的最新buffer會是更好的選擇.

计划中的2.0版本将尝试提供该功能，动态消耗缓冲区，以消除tcp累积延迟。

**Comment by oddengine** [comment]
已完成如下2个功能：自动释放缓冲区、消除累积延迟，以实现7x24小时直播。
v2.1.10 - Remove media segments within a specific time range to release memory usage.
v2.1.27 - Reduce latency by simply seeking.

更多功能参见[这里](https://github.com/studease/playease#features)
