### ISSUE TITLE
No buffering

### ISSUE THREAD

**Issue by ale07** [studease/playease#8]
I'm trying your video player.

I noticed that after a few minutes the streaming accumulates a delay of a few seconds due to my connection, that is correct, but the behavior I would like is that, in case of problems, streaming should align with the current vision without buffering.

How can I have this behavior?

thanks in advance for your reply and for your support.

**Comment by oddengine** [comment]
Hi,

There's no config or any easy way to achieve this. But you can set the currentTime to the last buffered time, by modifying the source code of flv render, or controlling it outside of the player.

```
video.currentTime = video.buffered.end(video.buffered.length - 1);
```

Otherwise, we are planning a feature of reducing cumulative delays due to tcp.

**Comment by ale07** [comment]
Hello,

Thanks for the reply.

In the first two cases could you tell me how to do it?

> video.currentTime = video.buffered.end (video.buffered.length - 1);

I will try this and let you know if it works.

Another thing, when I pause the video, after I can't play it anymore, but I have to click the reload button. Why of this behavior?

**Comment by ale07** [comment]
I would add that after pausing, when I click play the buffering and pause events are triggered consecutively.

**Comment by oddengine** [comment]
> I would add that after pausing, when I click play the buffering and pause events are triggered consecutively.

Emm, it's a bug.

**Comment by oddengine** [comment]
> Hello,
> 
> Thanks for the reply.
> 
> In the first two cases could you tell me how to do it?
> 
> > video.currentTime = video.buffered.end (video.buffered.length - 1);
> 
> I will try this and let you know if it works.
> 
> Another thing, when I pause the video, after I can't play it anymore, but I have to click the reload button. Why of this behavior?

You'll find the source code at v1.2.x branch. Try it in src/core/renders/playease.core.renders.flv.js

**Comment by oddengine** [comment]
> > Hello,
> > Thanks for the reply.
> > In the first two cases could you tell me how to do it?
> > > video.currentTime = video.buffered.end (video.buffered.length - 1);
> > 
> > 
> > I will try this and let you know if it works.
> > Another thing, when I pause the video, after I can't play it anymore, but I have to click the reload button. Why of this behavior?
> 
> You'll find the source code at v1.2.x branch. Try it in src/core/renders/playease.core.renders.flv.js

Or you can just get video element in your page:

```
var video = document.getElementsByTagName('video')[0];
```

**Comment by ale07** [comment]
Thank you for your support.

> > I would add that after pausing, when I click play the buffering and pause events are triggered consecutively.
> 
> Emm, it's a bug.

Could you a faster way to resolve it? if there is.



> > > Hello,
> > > Thanks for the reply.
> > > In the first two cases could you tell me how to do it?
> > > > video.currentTime = video.buffered.end (video.buffered.length - 1);
> > > 
> > > 
> > > I will try this and let you know if it works.
> > > Another thing, when I pause the video, after I can't play it anymore, but I have to click the reload button. Why of this behavior?
> > 
> > 
> > You'll find the source code at v1.2.x branch. Try it in src/core/renders/playease.core.renders.flv.js
> 
> Or you can just get video element in your page:
> 
> ```
> var video = document.getElementsByTagName('video')[0];
> ```

Yes, I tried it and this help me, it should be fine, thanks.


the last thing is that sometimes reloading does not always start immediately, but occasionally from some error, but this is a relative problem.

Thank you again.

**Comment by oddengine** [comment]
These two features below help supporting 7x24 live streaming.
v2.1.10 - Remove media segments within a specific time range to release memory usage.
v2.1.27 - Reduce latency by simply seeking.

More features [here](https://github.com/studease/playease#features)
